name: Frontend Linter

on:
  pull_request:
    paths:
      - frontend/**
  push:
    paths:
      - frontend/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v4
      - name: Install dependency
        run: pnpm install

      - name: Run Lint
        run: npm run lint
        working-directory: frontend
